const tutorialSidebar = [
  'README',
  {
    type: 'category',
    label: 'Tutorial: make something',
    collapsed: false,
    items: [
      'getting-started/installation',
      'getting-started/first-script',
      'tutorial/methods',
      'tutorial/flags',
      'tutorial/player-targets',
      'tutorial/variables-and-properties',
      'tutorial/decisions-and-time',
      'tutorial/hot-potato',
    ],
  },
  {
    type: 'category',
    label: 'Reference: exact behavior',
    items: [
      'getting-started/files-and-reloads',
      'language/methods-and-values',
      'language/variables-and-properties',
      'language/conditions-and-loops',
      'language/collections',
      'language/timing-and-yielding',
      'guides/flags-events-and-commands',
      'language/functions-scopes-and-errors',
      'guides/integrations',
      'guides/debugging',
      'guides/examples',
    ],
  },
  {
    type: 'category',
    label: 'Language catalog',
    link: {type: 'doc', id: 'reference/catalog'},
    items: [{type: 'autogenerated', dirName: 'reference'}],
  },
  {
    type: 'category',
    label: 'Validated examples',
    link: {type: 'doc', id: 'examples/index'},
    items: [{type: 'autogenerated', dirName: 'examples'}],
  },
  'language-specification',
  'translations',
  {
    type: 'category',
    label: 'Contributing',
    items: ['developer/project-guide'],
  },
];

export default {tutorialSidebar};
